[[dependency]]
org = "ballerina"
name = "mime"
version = "1.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "websubhub"
version = "0.2.0-alpha5"

[[dependency]]
org = "ballerinai"
name = "observe"
version = "0.9.0"

[[dependency]]
org = "ballerina"
name = "observe"
version = "0.9.0"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "1.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "time"
version = "1.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "1.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "lang.value"
version = "1.0.0"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "2.1.0-alpha5"


